#单元测试内置数据库
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:menu:fng;MODE:MySQL;MVCC:TRUE;LOCK_MODE=0;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=true
    username: sa
    password:
